"""empty message

Revision ID: dba99f8766f4
Revises: 
Create Date: 2024-09-30 21:44:42.413429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dba99f8766f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('confirmation_url', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('sites')
    # ### end Alembic commands ###
