"""empty message

Revision ID: 4dad84433d65
Revises: dba99f8766f4
Create Date: 2024-09-30 23:03:39.241421

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4dad84433d65'
down_revision: Union[str, None] = 'dba99f8766f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sites_urls'), 'sites', ['urls'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_urls'), table_name='sites')
    # ### end Alembic commands ###
